drop table T_PORTFOLIO_T_POSITION if exists
drop table T_POSITION_T_TRADE if exists
drop table T_ORDER if exists
drop table T_PORTFOLIO if exists
drop table T_ACCOUNT if exists
drop table T_POSITION if exists
drop table T_TRADE if exists


create table T_ACCOUNT (id bigint generated by default as identity (start with 1), cashBalance double, name varchar(255), primary key (id))
create table T_PORTFOLIO (id bigint generated by default as identity (start with 1), account_id bigint, name varchar(255), primary key (id))
create table T_ORDER (id bigint generated by default as identity (start with 1), portfolioName varchar(255), quantity bigint not null, status integer, symbol varchar(255), type integer, account_id bigint, primary key (id))
create table T_PORTFOLIO_T_POSITION (T_PORTFOLIO_id bigint not null, positions_id bigint not null, primary key (T_PORTFOLIO_id, positions_id), unique (positions_id))
create table T_POSITION (id bigint generated by default as identity (start with 1), numHeld bigint not null, symbol varchar(255), primary key (id))
create table T_POSITION_T_TRADE (T_POSITION_id bigint not null, tradeHistory_id bigint not null, primary key (T_POSITION_id, tradeHistory_id), unique (tradeHistory_id))
create table T_TRADE (id bigint generated by default as identity (start with 1), executionPrice double not null, quantity bigint not null, symbol varchar(255), type integer, primary key (id))

alter table T_PORTFOLIO add constraint FK_ACCOUNT_IN_ACCOUNT_PORTFOLIO foreign key (account_id) references T_ACCOUNT
alter table T_ORDER add constraint FK_ACCOUNT_ORDER foreign key (account_id) references T_ACCOUNT
alter table T_PORTFOLIO_T_POSITION add constraint FK_POSITION_IN_PORTFOLIO_POSITION foreign key (positions_id) references T_POSITION
alter table T_PORTFOLIO_T_POSITION add constraint FK_PORTFOLIO_IN_PORTFOLIO_POSITION foreign key (T_PORTFOLIO_id) references T_PORTFOLIO
alter table T_POSITION_T_TRADE add constraint FK_TRADE_HISTORY foreign key (tradeHistory_id) references T_TRADE
alter table T_POSITION_T_TRADE add constraint FK_POSITION_IN_POSITION_TRADE foreign key (T_POSITION_id) references T_POSITION

insert into T_ACCOUNT (cashBalance, name) values (500, 'John Smith')
insert into T_ACCOUNT (cashBalance, name) values (1000, 'Bernard Dupont')
insert into T_ACCOUNT (cashBalance, name) values (1500, 'Bart Simpson')

insert into T_PORTFOLIO (account_id,name) values (1,'John Smith - NASDAQ companies')
insert into T_PORTFOLIO (account_id,name) values (1,'John Smith - Emerging markets')
insert into T_PORTFOLIO (account_id,name) values (2,'Bernard Dupont - NASDAQ companies')
insert into T_PORTFOLIO (account_id,name) values (2,'Bernard Dupont - Emerging markets')
insert into T_PORTFOLIO (account_id,name) values (3,'Bart Simpson - NASDAQ companies')
insert into T_PORTFOLIO (account_id,name) values (3,'Bart Simpson - Emerging markets')




