# all profiles
logging.level:
    org.springframework: INFO
    org.hibernate: WARN


---
# profile "injectedProperty" only
spring:
  config:
    activate:
      on-profile: injectedProperty

customproperty: customPropValue

---
# profile "daoConfig" only
spring:
  config:
    activate:
      on-profile: daoConfig

  datasource:
    schema: classpath:/database/schema.sql
